export const socialIcon = [
  {
    link: "/",
    icon: "ri-facebook-fill",
  },
  {
    link: "/",
    icon: "ri-twitter-fill",
  },
  {
    link: "/",
    icon: "ri-github-fill",
  },
  {
    link: "/",
    icon: "ri-google-fill",
  },
];

export const langArray = [
  {
    title: "All",
    value: "objectivec+language:swift",
  },
  {
    title: "Java",
    value: "java",
  },
  {
    title: "Kotlin",
    value: "kotlin",
  },
  {
    title: "Flutter",
    value: "flutter",
  },
  {
    title: "React Native",
    value: "react-native",
  },
];
export const sortByArray = [
  {
    title: "Stars",
    value: "stars",
  },
  {
    title: "Last update",
    value: "updated",
  },
  {
    title: "Rating",
    value: "forks",
  },
  {
    title: "Help Issues",
    value: "help-wanted-issues",
  },
];

export const breakpointColumnsObj = {
  default: 3,
  1100: 3,
  700: 2,
  500: 1,
};

export const SingleOptions = [
  { value: "9-Patch", label: "9-Patch" },
  { value: "notion", label: "Notion" },
  { value: "Action Bars", label: "Action Bars" },
  { value: "Activities", label: "Activities" },
  { value: "ADB", label: "ADB" },
  { value: "Advertisements", label: "Advertisements" },
  { value: "Analytics", label: "Analytics" },
  { value: "Animations", label: "Animations" },
  { value: "ANR", label: "ANR" },
  { value: "AOP", label: "AOP" },
  { value: "API", label: "API" },
  { value: "APT", label: "APT" },
  { value: "Architecture", label: "Architecture" },
  { value: "Audio", label: "Audio" },
  { value: "Autocomplete", label: "Autocomplete" },
  { value: "BackgroundProcessing", label: "Background Processing" },
  { value: "BackwardCompatibility", label: "Backward Compatibility" },
  { value: "Badges", label: "Badges" },
  { value: "Bar Codes", label: "Bar Codes" },
  { value: "Benchmarking", label: "Benchmarking" },
  { value: "Bitmaps", label: "Bitmaps" },
  { value: "Bluetooth", label: "Bluetooth" },
  { value: "BlurEffects", label: "Blur Effects" },
  { value: "BreadCrumbs", label: "Bread Crumbs" },
  { value: "BRMS", label: "BRMS" },
  { value: "BrowserExtensions", label: "Browser Extensions" },
  { value: "BuildSystems", label: "Build Systems" },
  { value: "Bundles", label: "Bundles" },
  { value: "Buttons", label: "Buttons" },
  { value: "Caching", label: "Caching" },
  { value: "Camera", label: "Camera" },
  { value: "Canvas", label: "Canvas" },
  { value: "Cards", label: "Cards" },
  { value: "Carousels", label: "Carousels" },
  { value: "Changelog", label: "Changelog" },
  { value: "Checkboxes", label: "Checkboxes" },
  { value: "CloudStorages", label: "Cloud Storages" },
  { value: "ColorAnalysis", label: "Color Analysis" },
  { value: "ColorPickers", label: "Color Pickers" },
  { value: "Colors", label: "Colors" },
  { value: "Comet/Push", label: "Comet/Push" },
  { value: "CompassSensors", label: "Compass Sensors" },
  { value: "Conferences", label: "Conferences" },
  { value: "ContentProviders", label: "Content Providers" },
  { value: "ContinuousIntegration", label: "Continuous Integration" },
  { value: "CrashReports", label: "Crash Reports" },
  { value: "CreditCards", label: "Credit Cards" },
  { value: "Credits", label: "Credits" },
  { value: "CSV", label: "CSV" },
  { value: "Curl/Flip Effects", label: "Curl/Flip Effects" },
  { value: "DataBinding", label: "Data Binding" },
  { value: "DataGenerators", label: "Data Generators" },
  { value: "DataStructures", label: "Data Structures" },
  { value: "Database", label: "Database" },
  { value: "DatabaseBrowsers", label: "Database Browsers" },
  { value: "DateTimePickers", label: "Date Time Pickers" },
  { value: "Debugging", label: "Debugging" },
  { value: "Decomposers", label: "Decomposers" },
  { value: "DeepLinks", label: "Deep Links" },
  { value: "DependencyInjections", label: "Dependency Injections" },
  { value: "Design", label: "Design" },
  { value: "Design Patterns", label: "Design Patterns" },
  { value: "Dex", label: "Dex" },
  { value: "Dialogs", label: "Dialogs" },
  { value: "DistributedComputing", label: "Distributed Computing" },
  // { value: "DistributionPlatforms", label: "Distribution Platforms" },
  { value: "Download Managers", label: "Download Managers" },
  { value: "Drawables", label: "Drawables" },
  { value: "Emoji", label: "Emoji" },
  { value: "Emulators", label: "Emulators" },
  { value: "EPUB", label: "EPUB" },
  { value: "EventBuses", label: "Event Buses" },
  { value: "ExceptionHandling", label: "Exception Handling" },
  { value: "FaceRecognition", label: "Face Recognition" },
  { value: "FeedbackRatings", label: "Feedback Ratings" },
  { value: "FileSystem", label: "File System" },
  { value: "Fingerprint", label: "Fingerprint" },
  { value: "FloatingActionButtons", label: "Floating Action Buttons" },
  { value: "Fonts", label: "Fonts" },
  { value: "Forms", label: "Forms" },
  { value: "Fragments", label: "Fragments" },
  { value: "FRP", label: "FRP" },
  { value: "FSM", label: "FSM" },
  { value: "Functional Programming", label: "Functional Programming" },
  { value: "Gamepads", label: "Gamepads" },
  { value: "Games", label: "Games" },
  { value: "Geocaching", label: "Geocaching" },
  { value: "Gestures", label: "Gestures" },
  { value: "GIF", label: "GIF" },
  { value: "Graphics", label: "Graphics" },
  { value: "HTML", label: "HTML" },
  { value: "HTTP Mocking", label: "HTTP Mocking" },
  { value: "Icons", label: "Icons" },
  { value: "IDE", label: "IDE" },
  { value: "IDE Plugins", label: "IDE Plugins" },
  { value: "ImageCroppers", label: "Image Croppers" },
  { value: "ImageLoaders", label: "Image Loaders" },
  { value: "ImagePickers", label: "Image Pickers" },
  { value: "ImageProcessing", label: "Image Processing" },
  { value: "ImageViews", label: "Image Views" },
  { value: "Instrumentation", label: "Instrumentation" },
  { value: "Intents", label: "Intents" },
  { value: "Job Schedulers", label: "Job Schedulers" },
  { value: "JSON", label: "JSON" },
  { value: "Keyboard", label: "Keyboard" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "Layouts", label: "Layouts" },
  { value: "Library Demos", label: "Library Demos" },
  { value: "Localization", label: "Localization" },
  { value: "Location", label: "Location" },
  { value: "Logcat", label: "Logcat" },
  { value: "Logging", label: "Logging" },
  { value: "Mails", label: "Mails" },
  { value: "Maps", label: "Maps" },
  { value: "Markdown", label: "Markdown" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Maven Plugins", label: "Maven Plugins" },
  { value: "MBaaS", label: "MBaaS" },
  { value: "Media", label: "Media" },
  { value: "Menus", label: "Menus" },
  { value: "Messaging", label: "Messaging" },
  { value: "MIME", label: "MIME" },
  { value: "Navigation", label: "Navigation" },
  { value: "NDK", label: "NDK" },
  { value: "Networking", label: "Networking" },
  { value: "NFC", label: "NFC" },
  { value: "NoSQL", label: "NoSQL" },
  { value: "Permissions", label: "Permissions" },
  { value: "Physics Engines", label: "Physics Engines" },
  { value: "Platforms", label: "Platforms" },
  { value: "Plugin Frameworks", label: "Plugin Frameworks" },
  { value: "Preferences", label: "Preferences" },
  { value: "Progress Indicators", label: "Progress Indicators" },
  { value: "ProGuard", label: "ProGuard" },
  { value: "Properties", label: "Properties" },
  { value: "Protocol Buffer", label: "Protocol Buffer" },
  { value: "Pull To Refresh", label: "Pull To Refresh" },
  { value: "Purchases", label: "Purchases" },
  { value: "Push/Pull Notifications", label: "Push/Pull Notifications" },
  { value: "QR Codes", label: "QR Codes" },
  { value: "Quick Return", label: "Quick Return" },
  { value: "Radio Buttons", label: "Radio Buttons" },
  { value: "Range Bars", label: "Range Bars" },
  { value: "Ratings", label: "Ratings" },
  { value: "Recycler Views", label: "Recycler Views" },
  { value: "Resources", label: "Resources" },
  { value: "REST", label: "REST" },
  { value: "Ripple Effects", label: "Ripple Effects" },
  { value: "RSS", label: "RSS" },
  { value: "Screenshots", label: "Screenshots" },
  { value: "Scripting", label: "Scripting" },
  { value: "Scroll Views", label: "Scroll Views" },
  { value: "SDK", label: "SDK" },
  { value: "Search Inputs", label: "Search Inputs" },
  { value: "Security", label: "Security" },
  { value: "Sensors", label: "Sensors" },
  { value: "System", label: "System" },
  { value: "Tags", label: "Tags" },
  { value: "Task Managers", label: "Task Managers" },
  { value: "TDD BDD", label: "TDD BDD" },
  { value: "Template Engines", label: "Template Engines" },
  { value: "Testing", label: "Testing" },
  { value: "Testing Tools", label: "Testing Tools" },
  { value: "Text Formatting", label: "Text Formatting" },
  { value: "Text Views", label: "Text Views" },
  { value: "Text Watchers", label: "Text Watchers" },
  { value: "Text-to-Speech", label: "Text-to-Speech" },
  { value: "Toasts", label: "Toasts" },

  { value: "Tools", label: "Tools" },
  { value: "Tooltips", label: "Tooltips" },
  { value: "Trainings", label: "Trainings" },
  { value: "TV", label: "TV" },
  { value: "Twitter", label: "Twitter" },
  { value: "Updaters", label: "Updaters" },
  { value: "USB", label: "USB" },
  { value: "User Stories", label: "User Stories" },
  { value: "Utils", label: "Utils" },
  { value: "Validation", label: "Validation" },
  { value: "Video", label: "Video" },
  { value: "View Adapters", label: "View Adapters" },
  { value: "View Pagers", label: "View Pagers" },
  { value: "Views", label: "Views" },
  { value: "Watch Face", label: "Watch Face" },

  { value: "Wearables", label: "Wearables" },
  { value: "Weather", label: "Weather" },
  { value: "Web Tools", label: "Web Tools" },
  { value: "Web Views", label: "Web Views" },
  { value: "WebRTC", label: "WebRTC" },
  { value: "WebSockets", label: "WebSockets" },
  { value: "Wheel Widgets", label: "Wheel Widgets" },
  { value: "Wi-Fi", label: "Wi-Fi" },
  { value: "Widgets", label: "Widgets" },
  { value: "Windows", label: "Windows" },
  { value: "Wizards", label: "Wizards" },
  { value: "XML", label: "XML" },
  { value: "XMPP", label: "XMPP" },
  { value: "YAML", label: "YAML" },
  { value: "ZIP Codes", label: "ZIP Codes" },
];
